eureka_g6k_index:
    path:     /index
    methods: [ get ]
    defaults: { _controller: Devntech\G6K\Controller\IndexController::index }

eureka_g6k_fields:
    path:     /{simu}/Default/fields
    methods: [ post ]
    defaults: { _controller: Devntech\G6K\Controller\DefaultController::fields }

eureka_g6k_fields_try:
    path:     /{simu}/tryIt/Default/fields
    methods: [ post ]
    defaults: { _controller: Devntech\G6K\Controller\DefaultController::fieldsTryIt }

eureka_g6k_source:
    path:     /{simu}/Default/source
    methods: [ post ]
    defaults: { _controller: Devntech\G6K\Controller\DefaultController::source }

eureka_g6k_source_try:
    path:     /{simu}/tryIt/Default/source
    methods: [ post ]
    defaults: { _controller: Devntech\G6K\Controller\DefaultController::sourceTryIt }

eureka_g6k_calcul:
    path:     /{simu}
    methods: [ get, post ]
    defaults: { _controller: App\Controller\G6KController::calcul }

eureka_g6k_api:
    path:     /{simu}/api
    methods: [ get ]
    defaults: { _controller: Devntech\G6K\Controller\APIController::calcul }

eureka_g6k_calcul_view:
    path:     /{simu}/{view}
    methods: [ get, post ]
    defaults: { _controller: App\Controller\G6KController::calcul }

eureka_g6k_calcul_api_try:
    path:     /{simu}/api/tryIt
    methods: [ get ]
    defaults: { _controller: Devntech\G6K\Controller\APIController::tryIt }

eureka_g6k_calcul_view_try:
    path:     /{simu}/{view}/tryIt
    methods: [ get, post ]
    defaults: { _controller: Devntech\G6K\Controller\DefaultController::tryIt }

eureka_g6k_mail_send:
    path:     /{template}/{view}/mail
    methods: [ post ]
    defaults: { _controller: Devntech\G6K\Controller\MailController::sendMail }
